[tool.poetry]
name = "pylib-arpanrec"
version = "0.1.0"
description = "Common python API's"
authors = ["arpan <arpan.rec@gmail.com>"]
license = "GLWTS"
readme = "README.md"
package-mode = true

[tool.poetry.dependencies]
python = "^3.10"
requests = "2.32.3"
cryptography = "43.0.1"
hvac = "2.3.0"
prettytable = "3.11.0"

[tool.poetry.group.dev.dependencies]
pylint = "3.3.1"
black = "24.10.0"
isort = "5.13.2"
bandit = "1.7.10"
poetry-plugin-export = "1.8.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
